mod_version=1.0.0
maven_group=dev.ahmad
archives_base_name=pulseoptimize

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.1
fabric_version=0.136.0+1.21.11

java_version=21
modmenu_version=13.0.0
cloth_config_version=17.0.128

org.gradle.jvmargs=-Xmx512m -Xms256m -XX:MaxMetaspaceSize=256m
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.daemon=false
